### PR TITLE
Update OAC Remote Tests

### PR DESCRIPTION
**Pull request by pcowpert**
This PR revamps the remote tests for the OAC module to ideally be more stable.

### CODE REVIEW

**Comment by keflavich** [comment]
Could you rebase this against my branch?  The changes look fine, but there are some reversions here, I believe.

**Comment by pcowpert** [comment]
Okay, I rebased against the `fix_remote_stuff` branch and cleaned up our respective changes to `test_oac_remote.py`

**Comment by keflavich** [comment]
Strange, I'm still seeing the recently-merged VO stuff in the commit log.  Any idea what's going on?

**Comment by pcowpert** [comment]
Not sure. 

I updated my fork to be caught up with the current master when I first started debugging earlier this evening.  I guess we are slightly out of sync with each other?

**Comment by keflavich** [comment]
I manually merged this by cherry-picking the last commit

**Pull request closed without merging**
