### PR TITLE
Rebase on master and fix conflicts

### PR DESCRIPTION
**Pull request by migueldvb**
I have rebased the hitran branch on master and fixed the conflicts in `CHANGES` and `docs/index.rst`.

### CODE REVIEW

**Comment by keflavich** [comment]
Whoa... I am not entirely sure what to do with this.  I think *I* have to do the rebasing myself, because I can't just merge this.  I'm not sure github really supports friendly rebasing.  @bsipocz, do you know anything about this?

**Comment by migueldvb** [comment]
Yes, maybe better to fix this in your hitran branch.  You could discard e5c3ace to rebase without conflicts and these changes can be added later..

**Comment by keflavich** [comment]
OK, I rebased.  Now these match...

**Comment by keflavich** [comment]
Weird... I think this PR is broken.  I'm pretty sure both branches are identical except for commit names.

**Comment by migueldvb** [comment]
Sorry, I think the commit hashes changed when I rebased the branch. We can close this PR now?

**Comment by keflavich** [comment]
I think so.  You should double-check by rebasing against my branch and see if it goes to zero changes

**Comment by migueldvb** [comment]
Yes, that worked! Pushig the rebased branch closed this PR automatically.

**Comment by bsipocz** [comment]
>Whoa... I am not entirely sure what to do with this. I think I have to do the rebasing myself, because I can't just merge this. I'm not sure github really supports friendly rebasing. @bsipocz, do you know anything about this?

When you rebase, you need to force push the rebased version. But here you wanted to rebase the original branch in the fork compared to master in the main repo. To do that you need to have commit rights to @keflavich's branch to force push back the rebase. So it's expected not to work.

**Pull request closed without merging**
